check for gpg command

diff --git a/libexec/_gandalf b/libexec/_gandalf
--- a/libexec/_gandalf
+++ b/libexec/_gandalf
@@ -9,3 +9,8 @@ fi
 export GANDALF
 
 PATH="$PATH:$(dirname $BASH_SOURCE)"
+
+if [[ ! -x "$(type -P gpg 2>&-)" ]]; then
+  echo "ERROR: could not find gpg tool" 1>&2
+  false
+fi
