rudimentary working new, edit, and list passwords BUNDLE

diff --git a/libexec/list-passwords b/libexec/list-passwords
--- a/libexec/list-passwords
+++ b/libexec/list-passwords
@@ -4,8 +4,7 @@
 #/     list passwords -- list the passwords for a bundle
 #/
 #/ SYNOPSIS
-#/     list passwords [bundle]
-#/       the default bundle name is secrets
+#/     list passwords bundle
 
 # figure out the project root under which bin, lib live
 shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
@@ -13,11 +12,22 @@ shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
 # load a jason bourne library
 source "$shome/libexec/_jason"
 
-DEFINE_string "secrets" "secrets" "Name of secrets bundle in secrets/" "s"
+readonly cfg_gandalf="$shome/config/gandalf.yml"
 
 # entry point
 function main {
-  gpg -d "$shome/secrets/$FLAGS_secrets.yml.gpg"
+  if [[ "$#" = 0 ]]; then
+    log_fatal "missing name of secrets bundle"
+    exit 1
+  fi
+
+  readonly local nm_bundle="$1"; shift
+
+  gpg -a -d "$(secrets_path)/${nm_bundle}.yml.gpg"
+}
+
+function secrets_path {
+  ryaml "$cfg_gandalf" bundle "$nm_bundle" secrets_path
 }
 
 require sub "$BASH_SOURCE" "$@"
