split off gandalf demonstration, lots of cleanup

diff --git a/aloxec/new-secrets b/aloxec/new-secrets
--- a/aloxec/new-secrets
+++ b/aloxec/new-secrets
@@ -1,1 +1,43 @@
-new-bundle
+#!/bin/bash
+
+#/ NAME
+#/     new bundle -- create a new password bundle
+#/
+#/ SYNOPSIS
+#/     new bundle name
+
+# figure out the project root under which bin, lib live
+shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
+
+# load a jason bourne library
+source _jason
+require _gandalf "${GANDALF:-}"
+require _gandalf_
+
+readonly cfg_gandalf="$GANDALF/config/gandalf.yml"
+
+# entry point
+function main {
+  if [[ "$#" = 0 ]]; then
+    logger_fatal "missing name of secrets bundle"
+    exit 1
+  fi
+
+  readonly local nm_bundle="$1"; shift
+  readonly local tmp_keyring="$(mktemp -t XXXXXXXXX)"
+
+  set -x
+  keys
+  set +x
+
+  local _rcpt
+  for _rcpt in $(keys); do
+    gpg --no-default-keyring --keyring "$tmp_keyring" --import "$(keys_path)/$_rcpt"
+  done
+
+  echo "---" | gpg --no-default-keyring --keyring "$tmp_keyring" -a -e -o "$(secrets_path)/$nm_bundle.gpg" $(recipients)
+
+  rm -f "$tmp_keyring"
+}
+
+require _sub "$BASH_SOURCE" "$@"
